baseURL = "https://tnayuki.netlify.com/"
author = "tnayuki"
languageCode = "ja-jp"
title = "tnayuki"
theme = "black-and-light"
googleAnalytics = "UA-48560528-2"

[params]
  sitename = "tnayuki"

[[menu.main]]
    name = "Twitter"
    url  = "https://twitter.com/tnayuki"
